image: python:3.10

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-asyncio httpx

test-fastapi:
  stage: test
  script:
    - pytest -v